import { Routes } from '@angular/router';
import { Documentation } from './documentation/documentation';
import { Crud } from './crud/crud';
import { Empty } from './empty/empty';
import { DashboardComponent } from './dashboard/dashboard.component';
import { TaskManagerComponent } from './control/task-manager/task-manager.component';
import { ATMControlComponent } from './control/atm-control/atm-control.component';
import { PortManagerComponent } from './control/port-manager/port-manager.component';
import { NetworkControlComponent } from './control/network-control/network-control.component';
import { InstitutionComponent } from './Configuration/institution/institution.component';
import { BranchComponent } from './Configuration/branch/branch.component';
import { BinComponent } from './Configuration/bin/bin.component';
import { ATMTypeComponent } from './Configuration/atm-type/atm-type.component';
import { ATMComponent } from './Configuration/atm/atm.component';
import { ExternalBinComponent } from './Configuration/external-bin/external-bin.component';
import { FitComponent } from './Configuration/fit/fit.component';
import { CASSETComponent } from './Configuration/casset/casset.component';
import { PortComponent } from './Configuration/port/port.component';
import { TransactionComponent } from './Configuration/transaction/transaction.component';
import { AddEditViewAtmDetailsComponent } from './Configuration/atm/add-edit-view-atm-details/add-edit-view-atm-details.component';
import { AddExternalBinComponent } from './Configuration/external-bin/add-external-bin/add-external-bin.component';
import { ATMMonitoringComponent } from './monitorning/atm-monitoring/atm-monitoring.component';
import { HSMMonitoringComponent } from './monitorning/hsm-monitoring/hsm-monitoring.component';
import { NetworkMonitoringComponent } from './monitorning/network-monitoring/network-monitoring.component';
import { TxnMonitoringComponent } from './monitorning/txn-monitoring/txn-monitoring.component';
import { TransactionSearchComponent } from './monitorning/transaction-search/transaction-search.component';
import { AddFitComponent } from './Configuration/fit/add-fit/add-fit.component';
import { Component } from '@angular/core';
import { InternationalTXNEnabledDisabledComponent } from './riskManagement/international-txn-enabled-disabled/international-txn-enabled-disabled.component';
import { MCCBLOCKComponent } from './riskManagement/mcc-block/mcc-block.component';
import { RiskCOUNTRYBLOCKComponent } from './riskManagement/risk-country-block/risk-country-block.component';
import { RiskEcomSiteBLOCKComponent } from './riskManagement/risk-ecom-site-block/risk-ecom-site-block.component';
import { TXNALLOWWithoutPINComponent } from './riskManagement/t-xn-allow-without-pin/t-xn-allow-without-pin.component';
import { TxnAllowBlockedMCCComponent } from './riskManagement/txn-allow-blocked-mcc/txn-allow-blocked-mcc.component';
import { TxnAllowedRiskCountryComponent } from './riskManagement/txn-allowed-risk-country/txn-allowed-risk-country.component';
import { AtmMonitoringDetailsComponent } from './monitorning/atm-monitoring/atm-monitoring-details/atm-monitoring-details.component';
import { UpdateCasetteComponent } from './Configuration/casset/update-casette/update-casette.component';
import { AdminCardComponent } from './utility/admin-card/admin-card.component';
import { EmailUpdateComponent } from './utility/email-update/email-update.component';
import { SafManagementComponent } from './utility/saf-management/saf-management.component';
import { MobileUpdateComponent } from './utility/mobile-update/mobile-update.component';
import { AddEmailComponent } from './utility/email-update/add-email/add-email.component';
import { AddMobileComponent } from './utility/mobile-update/add-mobile/add-mobile.component';

export default [
    { path: 'documentation', component: Documentation },
    { path: 'crud', component: Crud },
    { path: 'empty', component: Empty },
    { path: 'dashboard', component: DashboardComponent },
    { path: 'task_Manager', component: TaskManagerComponent },
    { path: 'port_Manager', component: PortManagerComponent },
    { path: 'network_Control', component: NetworkControlComponent },
    { path: 'atm_control', component: ATMControlComponent },
    { path: 'institution', component: InstitutionComponent },
    { path: 'branch', component: BranchComponent },
    { path: 'bin', component: BinComponent },
    { path: 'atmType', component: ATMTypeComponent },
    { path: 'atm', component: ATMComponent },
    { path: 'add_edit_atm', component: AddEditViewAtmDetailsComponent },
    { path: 'externalBin', component: ExternalBinComponent },
    { path: 'add_externalBin', component: AddExternalBinComponent },
    { path: 'fit', component: FitComponent },
    { path: 'add_fit', component: AddFitComponent },
    { path: 'casset', component: CASSETComponent },
    { path: 'update_casset', component: UpdateCasetteComponent },
    { path: 'port', component: PortComponent },
    { path: 'transaction', component: TransactionComponent },
    { path: 'atm_Monitoring', component: ATMMonitoringComponent },
    { path: 'hsm_Monitoring', component: HSMMonitoringComponent },
    { path: 'network_Monitoring', component: NetworkMonitoringComponent },
    { path: 'transaction_Search', component: TransactionSearchComponent },
    { path: 'txn_Monitoring', component: TxnMonitoringComponent },
    { path: 'internationalTXNEnadisable', component: InternationalTXNEnabledDisabledComponent },
    { path: 'mccBlock', component: MCCBLOCKComponent },
    { path: 'riskCountryBlock', component: RiskCOUNTRYBLOCKComponent },
    { path: 'riskEcomSiteBlock', component: RiskEcomSiteBLOCKComponent },
    { path: 'txnAllowWithoutPin', component: TXNALLOWWithoutPINComponent },
    { path: 'txnAllowBlockedMCC', component: TxnAllowBlockedMCCComponent },
    { path: 'txnAllowedRiskCountry', component: TxnAllowedRiskCountryComponent },
     { path: 'admin_card', component: AdminCardComponent },
    { path: 'email_update', component: EmailUpdateComponent },
    { path: 'add_email_update', component: AddEmailComponent },
    { path: 'saf', component: SafManagementComponent },
    { path: 'mobile_update', component: MobileUpdateComponent },
    { path: 'add_mobile_update', component: AddMobileComponent },
    { path: '**', redirectTo: '/notfound' }

] as Routes;
