import { Component } from '@angular/core';
import { TableComponent } from "../../../layout/component/table/table.component";
import { CommonModule } from '@angular/common';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { Router } from '@angular/router';

@Component({
  selector: 'app-user-details',
  imports: [TableComponent, CommonModule, ButtonModule, DialogModule],
  templateUrl: './user-details.component.html',
  styleUrl: './user-details.component.scss'
})
export class UserDetailsComponent {

  rawData: any = [
    {
      "USERID": 26,
      "USERNAME": "TEST1",
      "USERPASSWORD": "feyoEjJI3MijvVnTR/Nc+mnb9p4=",
      "PROFILEID": "14",
      "FIRSTNAME": "TEST",
      "LASTNAME": "DEMO",
      "EMAILID": "demo@gmail.com",
      "USERSTATUS": "1",
      "DESCRIPTION": "---",
      "BRANCHCODE": "634",
      "IPADDRESS": "N",
      "RETRYCOUNT": 0,
      "USERBLOCK": "Not Blocked",
      "EXPIRYDATE": "N",
      "CREATIONDATE": 1720636200000,
      "LOGINSTATUS": 0,
      "FIRSTTIME": 1,
      "PASSWORDEXPIRYDATE": "N",
      "PASSWORDEXPIRYFLAG": 0,
      "MODIFIEDDATE": null,
      "INSTID": "TEST",
      "CREATEDUSERID": "24",
      "FORGOTPASSWORDFLAG": "0",
      "LASTLOGIN": "lstlogin",
      "USERTYPE": "M",
      "PSWREPEATCOUNT": "N",
      "FRSTLOGINDATE": "frstlogin",
      "FRSTLOGIN": "F",
      "FORCEPSWEXP": "N",
      "SALT_KEY": "gdW42pbpEoY=",
      "CHANGPASS_DATE": null,
      "ADDED_BY": "adminmaker",
      "ADDED_DATE": "11-jul-2024",
      "AUTH_STATUS": "1",
      "AUTH_BY": "adminchecker",
      "AUTH_DATE": "11-jul-2024",
      "REMARKS": "AUTHORIZED",
      "UNBLOCKED_BY": null,
      "UNBLOCKED_DATE": null,
      "UNBLOCK_AUTHBY": null,
      "UNBLOCK_AUTHDATE": null,
      "PASSWDRESET_BY": null,
      "PASSWDRESET_DATE": null,
      "PASSWD_RESETAUTHBY": null,
      "PASSWD_RESETDATE": null,
      "DELETED_BY": null,
      "DELETED_DATE": null,
      "DELETED_FLAG": null,
      "CBS_USERNAME": "TEST1",
      "MOBILENO": 9835457135,
      "DOB": 1720636200000,
      "COUNTRY": "India",
      "CITY": "chennai",
      "ADDRESS": "egmore",
      "PROFILE_PIC": null,
      "PROFILE_PIC_TYPE": null,
      "UNBLOCK_TIME": null,
      "BLOCKEDDATE": null,
      "PASS_COUNT": null,
      "BRANCHNAME": "HEAD OFFICE",
      "PROFILE_ID": 14,
      "PROFILE_NAME": "TESTMAKER"
    },
    {
      "USERID": 27,
      "USERNAME": "TEST2",
      "USERPASSWORD": "CIwuL8QJ7sN4COM4gBujnY4Kp3c=",
      "PROFILEID": "16",
      "FIRSTNAME": "test",
      "LASTNAME": "demo",
      "EMAILID": "demo@gmail.com",
      "USERSTATUS": "1",
      "DESCRIPTION": "---",
      "BRANCHCODE": "634",
      "IPADDRESS": "N",
      "RETRYCOUNT": 0,
      "USERBLOCK": "Not Blocked",
      "EXPIRYDATE": "N",
      "CREATIONDATE": 1720636200000,
      "LOGINSTATUS": 0,
      "FIRSTTIME": 1,
      "PASSWORDEXPIRYDATE": "N",
      "PASSWORDEXPIRYFLAG": 0,
      "MODIFIEDDATE": null,
      "INSTID": "TEST",
      "CREATEDUSERID": "24",
      "FORGOTPASSWORDFLAG": "0",
      "LASTLOGIN": "lstlogin",
      "USERTYPE": "C",
      "PSWREPEATCOUNT": "N",
      "FRSTLOGINDATE": "frstlogin",
      "FRSTLOGIN": "F",
      "FORCEPSWEXP": "N",
      "SALT_KEY": "GxbMQXxqzW4=",
      "CHANGPASS_DATE": null,
      "ADDED_BY": "adminmaker",
      "ADDED_DATE": "11-jul-2024",
      "AUTH_STATUS": "1",
      "AUTH_BY": "adminchecker",
      "AUTH_DATE": "11-jul-2024",
      "REMARKS": "AUTHORIZED",
      "UNBLOCKED_BY": null,
      "UNBLOCKED_DATE": null,
      "UNBLOCK_AUTHBY": null,
      "UNBLOCK_AUTHDATE": null,
      "PASSWDRESET_BY": null,
      "PASSWDRESET_DATE": null,
      "PASSWD_RESETAUTHBY": null,
      "PASSWD_RESETDATE": null,
      "DELETED_BY": null,
      "DELETED_DATE": null,
      "DELETED_FLAG": null,
      "CBS_USERNAME": "TEST2",
      "MOBILENO": 8964673621,
      "DOB": 1720636200000,
      "COUNTRY": "India",
      "CITY": "chennai",
      "ADDRESS": "egmore",
      "PROFILE_PIC": null,
      "PROFILE_PIC_TYPE": null,
      "UNBLOCK_TIME": null,
      "BLOCKEDDATE": null,
      "PASS_COUNT": null,
      "BRANCHNAME": "HEAD OFFICE",
      "PROFILE_ID": 16,
      "PROFILE_NAME": "TESTCHECKER"
    },
    {
      "USERID": 28,
      "USERNAME": "demomaker1",
      "USERPASSWORD": "y9uEeTwSwjVV/4HenpqVu3gppJs=",
      "PROFILEID": "17",
      "FIRSTNAME": "sowmiya",
      "LASTNAME": "sowmiya",
      "EMAILID": "sowmiya@gmail.com",
      "USERSTATUS": "1",
      "DESCRIPTION": "---",
      "BRANCHCODE": "000",
      "IPADDRESS": "N",
      "RETRYCOUNT": 0,
      "USERBLOCK": "Not Blocked",
      "EXPIRYDATE": "N",
      "CREATIONDATE": 1720981800000,
      "LOGINSTATUS": 0,
      "FIRSTTIME": 1,
      "PASSWORDEXPIRYDATE": "N",
      "PASSWORDEXPIRYFLAG": 0,
      "MODIFIEDDATE": null,
      "INSTID": "TEST",
      "CREATEDUSERID": "24",
      "FORGOTPASSWORDFLAG": "0",
      "LASTLOGIN": "lstlogin",
      "USERTYPE": "M",
      "PSWREPEATCOUNT": "N",
      "FRSTLOGINDATE": "frstlogin",
      "FRSTLOGIN": "F",
      "FORCEPSWEXP": "N",
      "SALT_KEY": "vwkHtt5+46g=",
      "CHANGPASS_DATE": null,
      "ADDED_BY": "adminmaker",
      "ADDED_DATE": "15-jul-2024",
      "AUTH_STATUS": "1",
      "AUTH_BY": "adminchecker",
      "AUTH_DATE": "15-jul-2024",
      "REMARKS": "AUTHORIZED",
      "UNBLOCKED_BY": null,
      "UNBLOCKED_DATE": null,
      "UNBLOCK_AUTHBY": null,
      "UNBLOCK_AUTHDATE": null,
      "PASSWDRESET_BY": null,
      "PASSWDRESET_DATE": null,
      "PASSWD_RESETAUTHBY": null,
      "PASSWD_RESETDATE": null,
      "DELETED_BY": null,
      "DELETED_DATE": null,
      "DELETED_FLAG": null,
      "CBS_USERNAME": "demomaker1",
      "MOBILENO": 8764587648,
      "DOB": 1720981800000,
      "COUNTRY": "India",
      "CITY": "chennai",
      "ADDRESS": "egmore",
      "PROFILE_PIC": null,
      "PROFILE_PIC_TYPE": null,
      "UNBLOCK_TIME": null,
      "BLOCKEDDATE": null,
      "PASS_COUNT": null,
      "BRANCHNAME": "Head Office",
      "PROFILE_ID": 17,
      "PROFILE_NAME": "MakerDemo"
    },
    {
      "USERID": 29,
      "USERNAME": "demochecker2",
      "USERPASSWORD": "dxPzdii2je/afcY/qHOGHO2pQ+4=",
      "PROFILEID": "18",
      "FIRSTNAME": "sowmiya",
      "LASTNAME": "s",
      "EMAILID": "sowmiya@gmail.com",
      "USERSTATUS": "1",
      "DESCRIPTION": "---",
      "BRANCHCODE": "000",
      "IPADDRESS": "N",
      "RETRYCOUNT": 0,
      "USERBLOCK": "Not Blocked",
      "EXPIRYDATE": "N",
      "CREATIONDATE": 1720981800000,
      "LOGINSTATUS": 0,
      "FIRSTTIME": 1,
      "PASSWORDEXPIRYDATE": "N",
      "PASSWORDEXPIRYFLAG": 0,
      "MODIFIEDDATE": null,
      "INSTID": "TEST",
      "CREATEDUSERID": "24",
      "FORGOTPASSWORDFLAG": "0",
      "LASTLOGIN": "lstlogin",
      "USERTYPE": "C",
      "PSWREPEATCOUNT": "N",
      "FRSTLOGINDATE": "frstlogin",
      "FRSTLOGIN": "F",
      "FORCEPSWEXP": "N",
      "SALT_KEY": "J9/uUXblB+A=",
      "CHANGPASS_DATE": null,
      "ADDED_BY": "adminmaker",
      "ADDED_DATE": "15-jul-2024",
      "AUTH_STATUS": "1",
      "AUTH_BY": "adminchecker",
      "AUTH_DATE": "15-jul-2024",
      "REMARKS": "AUTHORIZED",
      "UNBLOCKED_BY": null,
      "UNBLOCKED_DATE": null,
      "UNBLOCK_AUTHBY": null,
      "UNBLOCK_AUTHDATE": null,
      "PASSWDRESET_BY": null,
      "PASSWDRESET_DATE": null,
      "PASSWD_RESETAUTHBY": null,
      "PASSWD_RESETDATE": null,
      "DELETED_BY": null,
      "DELETED_DATE": null,
      "DELETED_FLAG": null,
      "CBS_USERNAME": "demochecker2",
      "MOBILENO": 5475675687,
      "DOB": 1720981800000,
      "COUNTRY": "Haiti",
      "CITY": "chennai",
      "ADDRESS": "egmore",
      "PROFILE_PIC": null,
      "PROFILE_PIC_TYPE": null,
      "UNBLOCK_TIME": null,
      "BLOCKEDDATE": null,
      "PASS_COUNT": null,
      "BRANCHNAME": "Head Office",
      "PROFILE_ID": 18,
      "PROFILE_NAME": "CheckerDemo"
    },
    {
      "USERID": 30,
      "USERNAME": "makeradmin",
      "USERPASSWORD": "brVBXlNORZH7MlNPYw6dOswj3H8=",
      "PROFILEID": "19",
      "FIRSTNAME": "sowmiya",
      "LASTNAME": "sowmiya",
      "EMAILID": "sowmiya@gmail.com",
      "USERSTATUS": "1",
      "DESCRIPTION": "---",
      "BRANCHCODE": "000",
      "IPADDRESS": "N",
      "RETRYCOUNT": 0,
      "USERBLOCK": "Not Blocked",
      "EXPIRYDATE": "N",
      "CREATIONDATE": 1720981800000,
      "LOGINSTATUS": 0,
      "FIRSTTIME": 1,
      "PASSWORDEXPIRYDATE": "N",
      "PASSWORDEXPIRYFLAG": 0,
      "MODIFIEDDATE": null,
      "INSTID": "TEST",
      "CREATEDUSERID": "24",
      "FORGOTPASSWORDFLAG": "0",
      "LASTLOGIN": "lstlogin",
      "USERTYPE": "M",
      "PSWREPEATCOUNT": "N",
      "FRSTLOGINDATE": "frstlogin",
      "FRSTLOGIN": "F",
      "FORCEPSWEXP": "N",
      "SALT_KEY": "q/q3zSArHSw=",
      "CHANGPASS_DATE": null,
      "ADDED_BY": "adminmaker",
      "ADDED_DATE": "15-jul-2024",
      "AUTH_STATUS": "1",
      "AUTH_BY": "adminchecker",
      "AUTH_DATE": "15-jul-2024",
      "REMARKS": "AUTHORIZED",
      "UNBLOCKED_BY": null,
      "UNBLOCKED_DATE": null,
      "UNBLOCK_AUTHBY": null,
      "UNBLOCK_AUTHDATE": null,
      "PASSWDRESET_BY": null,
      "PASSWDRESET_DATE": null,
      "PASSWD_RESETAUTHBY": null,
      "PASSWD_RESETDATE": null,
      "DELETED_BY": null,
      "DELETED_DATE": null,
      "DELETED_FLAG": null,
      "CBS_USERNAME": "makeradmin",
      "MOBILENO": 8456757657,
      "DOB": 1720981800000,
      "COUNTRY": "India",
      "CITY": "chennai",
      "ADDRESS": "egmore",
      "PROFILE_PIC": null,
      "PROFILE_PIC_TYPE": null,
      "UNBLOCK_TIME": null,
      "BLOCKEDDATE": null,
      "PASS_COUNT": null,
      "BRANCHNAME": "Head Office",
      "PROFILE_ID": 19,
      "PROFILE_NAME": "demoadmin1"
    },
    {
      "USERID": 31,
      "USERNAME": "checkeradmin",
      "USERPASSWORD": "SX/CNTVuVeiaCw9kHz0zpZjXkxE=",
      "PROFILEID": "20",
      "FIRSTNAME": "sowmiya",
      "LASTNAME": "s",
      "EMAILID": "sowmiya@gmail.com",
      "USERSTATUS": "1",
      "DESCRIPTION": "---",
      "BRANCHCODE": "453",
      "IPADDRESS": "N",
      "RETRYCOUNT": 0,
      "USERBLOCK": "Not Blocked",
      "EXPIRYDATE": "N",
      "CREATIONDATE": 1720981800000,
      "LOGINSTATUS": 0,
      "FIRSTTIME": 1,
      "PASSWORDEXPIRYDATE": "N",
      "PASSWORDEXPIRYFLAG": 0,
      "MODIFIEDDATE": null,
      "INSTID": "TEST",
      "CREATEDUSERID": "24",
      "FORGOTPASSWORDFLAG": "0",
      "LASTLOGIN": "lstlogin",
      "USERTYPE": "C",
      "PSWREPEATCOUNT": "N",
      "FRSTLOGINDATE": "frstlogin",
      "FRSTLOGIN": "F",
      "FORCEPSWEXP": "N",
      "SALT_KEY": "z5y6B4qmZ3Y=",
      "CHANGPASS_DATE": null,
      "ADDED_BY": "adminmaker",
      "ADDED_DATE": "15-jul-2024",
      "AUTH_STATUS": "1",
      "AUTH_BY": "adminchecker",
      "AUTH_DATE": "15-jul-2024",
      "REMARKS": "AUTHORIZED",
      "UNBLOCKED_BY": null,
      "UNBLOCKED_DATE": null,
      "UNBLOCK_AUTHBY": null,
      "UNBLOCK_AUTHDATE": null,
      "PASSWDRESET_BY": null,
      "PASSWDRESET_DATE": null,
      "PASSWD_RESETAUTHBY": null,
      "PASSWD_RESETDATE": null,
      "DELETED_BY": null,
      "DELETED_DATE": null,
      "DELETED_FLAG": null,
      "CBS_USERNAME": "checkeradmin",
      "MOBILENO": 9567745877,
      "DOB": 1720981800000,
      "COUNTRY": "India",
      "CITY": "chennai",
      "ADDRESS": "egmore",
      "PROFILE_PIC": null,
      "PROFILE_PIC_TYPE": null,
      "UNBLOCK_TIME": null,
      "BLOCKEDDATE": null,
      "PASS_COUNT": null,
      "BRANCHNAME": "TEST OFFICE",
      "PROFILE_ID": 20,
      "PROFILE_NAME": "demoadmin2"
    }
  ];
  globalFilterFields: any = [
    "USERID",
    "USERNAME",
    "INSTID",
    "ADDED_BY",
    "ADDED_DATE",
    "PROFILE_NAME"
  ];
  cols: any = [
    { field: 'USERNAME', header: 'USERNAME' },
    { field: 'USERID', header: 'USER ID', sort: true, type: 'number' },
    { field: 'INSTID', header: 'INST ID', sort: true, type: 'string' },
    { field: 'PROFILE_NAME', header: 'PROFILE NAME', sort: true, type: 'string' },
    { field: 'ADDED_DATE', header: 'ADDED DATE', sort: true, type: 'date' },
    { field: 'ADDED_BY', header: 'ADDED BY', sort: true, type: 'string' },
    { field: 'Action', header: 'Action', type: ['view', 'edit', 'delete'] },
  ]
  buttonsList: any = [
    { label: 'Add User', icon: 'pi pi-user-plus', type: 'addUser', variant: 'raised', severity: "primary" },
    { label: 'Block User', icon: 'pi pi-lock', type: 'blockUser', variant: 'outlined', severity: "danger" },
    { label: 'Unblock User', icon: 'pi pi-lock-open', type: 'unblockUser', variant: 'outlined', severity: "warn" },
    { label: 'Reset Password', icon: 'pi pi-refresh', type: 'resetPassword', variant: 'outlined', severity: "primary" }
  ];
  delete_visible: boolean = false;
  constructor(private router: Router) { };
  MultiButton(event: any) {

    if (event.type == 'addUser') {
      this.router.navigate(['/pages/add_user'], { state: { data: event?.data, type: event?.type } });
    } else if (event.type == 'blockUser') {
      this.router.navigate(['/pages/block_user'], { state: { data: event?.data, type: event?.type } });
    } else if (event.type == 'unblockUser') {
      this.router.navigate(['/pages/unblock_user'], { state: { data: event?.data, type: event?.type } });
    } else if (event.type == 'resetPassword') {
      this.router.navigate(['/pages/reset_user_password'], { state: { data: event?.data, type: event?.type } });
    }
  }

  delateData() {
    this.delete_visible = false;
  }

  editView(event: any, type: any) {
    this.router.navigate(['/pages/add_user'], { state: { data: event?.data, type: type } });
  }

}
